Dockerfile
docker-compose.yml

This is what I had to do to get hot reloads to work when running the docker container on Linux. Additional work may be required on windows. It only works for hot reloading the client files. For the node server it might take something like Nodemon. Feel free to disregard if you don't think it's useful.
https://stackoverflow.com/questions/44176922/docker-container-doesnt-reload-angular-app

Enable hot reloads for docker

---

test/server/cards/Ashes-Core/ButterflyMonk.spec.js
test/server/cards/Ashes-Core/Gilder.spec.js

I added tests for the butterfly monk. I could not replicate the issue of the inexhaustible not firing.  Also added a test case to the gilder to make sure it was firing when destroyed while blocking, which it appears to be.

added tests for butterfly monk and gilder on destroyed

---

test/server/cards/Ashes-Core/StormwindSniper.spec.js

Couldn't replicate the issue, but I added some test cases around it.

add unit tests to stormwind-sniper for PB abilities

---

server/game/cards/Ashes-Core/AradelSummergaard.js
server/game/cards/Ashes-Core/ParticleShield.js
test/server/cards/Ashes-Core/ParticleShield.spec.js

Implementation for Particle Shield. Also includes an Aradel fix discovered in testing (she should be allowed to target her own units).

Implement particle shield

---

server/game/cards/Ashes-Core/ShadowSpirit.js
server/game/cards/Ashes-Core/SummonShadowSpirit.js
test/helpers/playerinteractionwrapper.js
test/server/cards/Ashes-Core/ShadowSpirit.spec.js
test/server/cards/Ashes-Core/SummonShadowSpirit.spec.js

Shadow Spirit implementation including summons. I also added a method to the test helper for clicking on an opponent's die.

Implementation for shadow spirit

---

server/game/cards/Ashes-Core/FlashArcher.js
test/server/cards/Ashes-Core/BloodArcher.spec.js
test/server/cards/Ashes-Core/FlashArcher.spec.js

Issue 148:
issue was leftover copy and paste from creating flash archer.

Fixed blood archer by fixing flash archer

---

data/cards/all-cards.json

fix dread wraith recover value

---

test/server/cards/Ashes-Core/UndyingHeart-BUG.spec.js

Issue 149:
I added a test case, but I couldn't replicate the issue.

Added test case for blood archer dying to fear

---

server/game/cards/Ashes-Core/ToShadows.js
test/server/cards/Ashes-Core/ToShadows.spec.js

To Shadows implementation and test. Pretty straightforward.

To Shadows implementation and test

---

server/game/cards/Mixed-Expansions/SummonGhostlyMount.js

Trivial one, but let me know if I missed anything 😃

Summon Ghostly Mount exhaustion fix

---

server/game/cards/Deluxe/StandardBearer.js
test/server/cards/StandardBearer.spec.js

Standard Bearer now can only target attacking units (BUG #610)

---

server/game/Die.js
server/game/cards/Ashes-Core/CoalRoarkwin.js
server/game/cards/Time/RubyCobra.js

Time die selection prompts added. Sympathy die prompt clarified.

Update prompts for dice powers, Slash, and Ruby Cobra effect

---

server/game/cards/Ashes-Core/BloodTransfer.js
server/game/cards/Mixed-Expansions/EssenceDruid.js

Essence Druid and Blood Transfer changed to optional to match card wording

Optional trigger fixes

---

server/game/cards/Deluxe/SummonWingedLioness.js
test/server/cards/SummonWingedLioness.spec.js

Automate winged lioness summon

---

server/game/cards/Time/SunshieldSentry.js
test/server/cards/StrangeCopy.spec.js
test/server/cards/SunshieldSentry.spec.js

example text 
bdw1 uses Sunshield Sentry to block against Fallen
bdw1 has chosen defenders
bdw1 uses Sunshield Sentry to remove Mist Spirit from battle

Add sunshield sentry

---

server/game/cards/Time/FateReflection.js
test/server/cards/FateReflection.spec.js

Fate Reflection implementation. I should probably add tests for Golden Veil and Angelic Rescue, but will do that another time.

Fate Reflection implementation and tests

---

server/game/Card.js
server/game/cards/Deluxe/LawOfDomination.js
server/game/cards/Mixed-Expansions/AncestorSpirit.js
server/game/cards/Mixed-Expansions/PolarityMage.js
test/server/cards/AshSpirit.spec.js

also fix broken polarity mage and law of domination targeting

Fix ash spirit destroying things when other units are destroyed

---

data/decks/precon-core.json

Update precons to add Echo and Astrea

---

server/game/cards/Time/RileTheMeek.js
test/server/cards/RileTheMeek.spec.js

rile the meek pings are optional

---

server/game/GameActions/DrawAction.js
server/game/cards/Time/Generosity.js
test/server/cards/GatesThrownOpen.spec.js
test/server/cards/Generosity.spec.js

still need generosity tests
messaging works well
Turn 1 - bdw1
bdw1 plays Generosity to choose from 3 actions
bdw1 removes 1 exhaustion token from Orrick Gilstream
bdw2 heals 2 damage from Astrea
bdw1 draws 3 cards

Add generosity

---

server/game/cards/Mixed-Expansions/SummonSpectralAssassin.js

Add message to Spectral Assassin draw

---

server/game/cards/Mixed-Expansions/PainShaman.js
server/game/cards/Mixed-Expansions/SummonMindFogOwl.js
server/game/cards/Mono-Expansions/FlashArcher.js

Optional targetting for Mind Fog Owl Focus 1 and Flash Archer. Select box wording for Pain Shaman. Relates to issue #643 but were smaller issues that I could fix during the card audit.

Feature optional

---

server/game/cards/Time/FlockShepherd.js
test/server/cards/FlockShepherd.spec.js

https://discord.com/channels/356912698451296276/752956497947787404/885700747273076757
feels a little weird to just say "any reactions" and not listing out what the reactions are. but i think that's standard?

gather is optional

---

server/game/cards/Ashes-Core/CutTheStrings.js
server/game/cards/Deluxe/Encore.js
server/game/cards/Deluxe/SquallStallion.js
server/game/cards/Mixed-Expansions/MarkOfTheGoddess.js
server/game/cards/Mixed-Expansions/SummonWeepingSpirit.js
server/game/cards/Mono-Expansions/SummonOrchidDove.js

Consistently use choose instead of select

Prompt message updates

---

server/game/Card.js
test/server/cards/FlockShepherd.spec.js
test/server/cards/RileTheMeek.spec.js

printed attacks of X should not default to 0 (#650)

---

server/game/Card.js
server/game/cards/Ashes-Core/BoundSoul.js
server/game/cards/Ashes-Core/FalseDemon.js
server/game/cards/Ashes-Core/OneHundredBlades.js
server/game/cards/Time/Backtrack.js

Effect messages update

---

docs/development-process.md
server/game/cards/Mixed-Expansions/MassHeal.js
test/server/cards/MassHeal.spec.js

Fix for Task 4 of #643. I haven't worked out how to fix the efect message yet, but that was an existing issue.

Select which Mass Heal option a player wants

---

server/game/cards/Time/CanyonShelter.js
test/server/cards/CanyonShelter.spec.js

add status token when canyon shelter returns unit

---

server/game/cards/Time/SunshieldSentry.js
test/server/cards/FlashStrike.spec.js

flash strike is after blockers are declared, not when

---

server/game/Die.js
server/game/cards/Ashes-Core/BoundSoul.js
server/game/cards/Mixed-Expansions/RevivalPact.js

Minor improvements to prompts.
Fixes:
No longer says "Choose a Ally" or "Choose 3 Allies" for the cards.
Dice prompts are more specific about what they will do. I think some of the wording could be improved, as ending with words like "to" in order to start with "Choose" feels a bit clunky.

Feature messages

---

server/game/cards/Mono-Expansions/BodyInversion.js
test/server/cards/BodyInversion.spec.js

Added test to body inversion spec, and deal explicitly with Printed Attack = X, which should fix Silver Snake (tested), Mirror Spirit and Squall Stallion.

Fix bug #697: Body Inversion

---

server/game/gamesteps/setup/FirstFivePrompt.js

This aims to resolve #576 by drawing FF cards into a player's hand as they select them, greying out cards from deck that cannot be selected due to already having been selected, and having a clear FF button so that you can easily start selecting FF from scratch. I noticed that there aren't any explicit tests of FF selection; I'm not sure how to do that.

Feature - draw FF into hand

---

test/server/cards/LightBringer.spec.js
test/server/cards/SacredGround.spec.js
test/server/cards/safeguard.spec.js

fixes #666 
this isn't implemented yet

fix round boundary issues for lightbringer, sacred ground, and safeguard

---

server/game/gamesteps/MeditatePrompt.js

Fix cancel not resetting dice (issue #710) and being able to change opponent's dice (issue #698)

Fix 2 meditate bugs

---

server/game/cards/Deluxe/LawOfAssurance.js
server/game/cards/Deluxe/LawOfDomination.js
server/game/cards/Deluxe/LawOfSight.js
server/game/cards/Mixed-Expansions/LawOfFear.js
server/game/cards/Mixed-Expansions/LawOfGrace.js
test/server/cards/LawOfAssurance.spec.js
test/server/cards/LawOfDomination.spec.js

Updated tests for Laws of Assurance and Domination to confirm that this was working.

Fix bug #708 Law effects should stop when exhausted

---

server/game/cards/Ashes-Core/SummonSilverSnake.js

Make Summon Silver Snake focus maximum 2

Limit SummonSilverSnake focus ability

---

server/game/cards/Mixed-Expansions/SummonMindFogOwl.js

This prompt should aid players in the situation described in issue #722

Improve message for Summon Mind Fog Owl

---

server/game/CardSelectors/ExactlyXCardSelector.js
server/game/CardSelectors/SingleCardSelector.js
server/game/CardSelectors/UpToXCardSelector.js
server/game/cards/Ashes-Core/BoundSoul.js

Prompts are now _Choose an ally_ or _Choose X allies_
Previously it was _Choose a Ally_ or _Choose X Allys_

Feature ally selection messages

---

server/game/cards/Mixed-Expansions/PolarityMage.js
server/game/cards/Mixed-Expansions/SummonSpectralAssassin.js
server/game/cards/Mono-Expansions/Anguish.js
test/server/cards/Anguish.spec.js
test/server/cards/Copycat.spec.js
test/server/cards/SummonSpectralAssassin.spec.js

Minor improvements to the wording of player choices

Choice message improvements

---

server/game/cards/Ashes-Core/Anchornaut.js
server/game/cards/Ashes-Core/ChantOfRevenge.js
server/game/cards/Ashes-Core/Cover.js
server/game/cards/Ashes-Core/FalseDemon.js
server/game/cards/Ashes-Core/JessaNaNi.js
server/game/cards/Ashes-Core/MistTyphoon.js
server/game/cards/Ashes-Core/OneHundredBlades.js
server/game/cards/Mono-Expansions/Remorse.js

Added a damage message when Remorse deals damage
Removed the dealDamage amount when it is 1

Remorse damage message and remove defaults

---

server/game/gamesteps/ChooseDefendersPrompt.js

Change guard message to info level in log

---

server/game/cards/Ashes-Core/Purge.js
test/server/cards/Purge-focus.spec.js
test/server/cards/Purge.spec.js

Purge targets

---

test/server/cards/DoubleDown.spec.js

Corrected Double Down test

---

server/game/cards/Time/Ensnare.js
server/game/gamesteps/triggeredabilitywindow.js
server/game/gamesteps/triggeredabilitywindowtitles.js
test/server/cards/DoubleDown.spec.js
test/server/cards/Ensnare.spec.js
test/server/cards/FlashStrike.spec.js

Ensnare basic functionality and test

Feature ensnare

---

server/game/cards/Time/BlessingOfLightning.js
server/game/cards/Time/RaywardKnight.js
server/game/cards/Time/RaywardRecruit.js
server/game/cards/Time/SummonWishingWing.js

Miscellaneous message improvements

Minor review of messages

---

server/game/cards/Time/RealmWalker.js
test/server/cards/RealmWalker.spec.js

Made the reaction a ForcedReaction so it always triggers if it can, and corrected the event message

Fix Bug#911 and correct messages

---

server/game/cards/Time/FoxSpirit.js
test/server/cards/SummonFoxSpirit.spec.js

Fox Spirit pounce check and test

---

server/game/cards/Ashes-Core/AradelSummergaard.js
server/game/cards/Ashes-Core/BloodTransfer.js
server/game/cards/Ashes-Core/FalseDemon.js
server/game/cards/Time/CanyonShelter.js
server/game/cards/Time/RaywardKnight.js
server/game/cards/Time/RaywardRecruit.js
server/game/cards/Time/Reinforce.js
server/scripts/ashes/importprecons.js

Minor message wording improvements

Feature effect messages

---

server/game/cards/Mixed-Expansions/Hollow.js
server/game/cards/Mono-Expansions/ShadowSpirit.js
server/game/cards/Time/DreamFracture.js
server/game/cards/Time/DreamlockMage.js
server/game/cards/Time/FoxSpirit.js
test/server/cards/BloodShaman.spec.js
test/server/cards/SummonFoxSpirit.spec.js

All the Raise and Lower dice except for Blood Shaman, as the diecondition check doesn't play nicely with Undying Heart

All LowerDice corrections, 1 RaiseDie correction

---

server/game/GameActions/DealDamageAction.js
test/server/attack-phoenixborn-exhaustion.spec.js

Test sonic pulse and quick strike

---

server/game/cards/Mixed-Expansions/PolarityMage.js
test/server/cards/PolarityMage.spec.js

Bug #861 to address the button readability

Shortened decision buttons

---

server/game/cards/Mixed-Expansions/ReturnToSoil.js
test/server/cards/ReturnToSoil.spec.js

Return to Soil now mills controlling player's deck and removes from their discard pile

---

server/game/cards/Time/SurvivalOfTheFittest.js
test/server/cards/SurvivalOfTheFittest.spec.js

Survival as AOE

---

server/game/cards/Time/Keepsake.js
test/server/cards/Keepsake.spec.js

Array for changedDice didn't match the expected result, so added changedDice[0] to both the logic check and the amount calculation

Bug fix #938: Void Pulse should trigger Keepsake

---

client/RestrictedList.js
server/game/cards/Time/DoubleDown.js
test/helpers/gameflowwrapper.js
test/helpers/playerinteractionwrapper.js
test/server/cards/DoubleDown.spec.js

Restricted number of conjurations that would be created by Double Down and corrected intermittent test failure

Corrected Double Down Conjuration Count Limit

---

server/game/cards/Time/Ensnare.js
test/server/cards/Ensnare.spec.js

Also added test that now passes

Correct Ensnare trigger

---

server/game/cards/Mixed-Expansions/MarkOfTheGoddess.js
test/server/cards/MarkOfTheGoddess.spec.js

Bug fix #950 - added test and fixed the logic

Mark of the Goddess Targetting Bug Fix

---

README.md

line 110 - updated filepath to "server/scripts/user/makeSuperuser"

Update README with correct filepath for makeSuperuser script

---

test/server/cards/DoubleDown.spec.js

https://github.com/Ashteki/ashteki/issues/1471
I was unable to reproduce the reported bug with this test.

1471 fix: Add test for Frost Frog + Double Down vs. Whiplash
