Ashteki/ashteki

- server/game/gamesteps/main/actionwindow.js
- test/helpers/playerinteractionwrapper.js
Update end of turn confirmation to only trigger if main action has not been used. Also updated verbiage of confirmation to indicate that it is the main action being passed. Left legal actions check so that if there are no legal actions, prompt is still skipped.
> update end of turn confirmation

- server/game/cards/Ashes-Core/DeepFreeze.js
- test/server/cards/Ashes-Core/DeepFreeze.spec.js
Issue 121
Problem was the the target of the discard ability was the unit. Followed the same pattern as the remove status token ability. Also added a test case for this.
> Added target for deep freeze discard and test case

- server/game/cards/Ashes-Core/Empower.js
- test/server/cards/Ashes-Core/Empower-focus.spec.js
Issue 91:
Instead of making the whole then optional, I made the tokenBoy portion optional. This also then required a check in the amount section to verify that tokenBoy isn't undefined. Uncommented the test you already had.
> make empoer focus ability optional

- server/game/Card.js
- server/game/cards/Ashes-Core/BodyInversion.js
- server/game/cards/Ashes-Core/SilverSnake.js
- server/game/effects.js
- test/server/cards/Ashes-Core/BodyInversion.spec.js
**Body Inversion**
Hard part on this one was Silver Snake since it's printed value is technically equal to X instead of being like Dreaded Wraith where it's an attack buff. To handle this, I had to add new effects (`setPrintedAttack` and `setPrintedLife`). This allows the adjustment of the printed values without having to actually change the values. The only use case for this with Body Inversion so far seems to be the snake but hopefully it's extensible.
Only thing I'm slightly uncertain about is whether to give precedence to a copy effect or a printed value effect. I decided to go with the copy effect since it seems more likely that will be layered after setting printed values. If this causes issues then it might be worth adding a method to determine which of the two is more recent, but …
> Implement body inversion

- server/game/cards/Time/EmberootLizard.js
Partial fix for BUG #609. I expanded on the Ignite ability message and noticed that ShowMessage = False by default in dealDamageAction, so I set ShowMessage = True for the Lizard so that if a unit is damaged there is a message that this occurred.
Ideally, there would be two messages, the first saying that the Emberoot Lizard had its attack value increased, and second that it was used to deal 1 damage to the target.
> Emberoot lizard bug fix

- server/game/cards/Mixed-Expansions/AngelicRescue.js
- server/game/cards/Time/FateReflection.js
- test/server/cards/AngelicRescue.spec.js
- test/server/cards/FateReflection.spec.js
- test/server/cards/Redirect.spec.js
Angelic Rescue and Fate Reflection now confirm that the triggered damage target is controlled by the player holding the reaction spell. Fate Reflection tests updated to add this check.
> Bug fix #634

- server/game/GameActions/RemoveTokenAction.js
- server/game/cards/Mixed-Expansions/PainShaman.js
Pain Shaman now creates the following event messages when played:
test2 plays Pain Shaman
test2 uses Pain Shaman to deal 1 damage to Shining Hydra
test2 uses Pain Shaman to remove 1 damage token from Shining Hydra
> Pain Shaman message fix

- server/game/gamesteps/MeditatePrompt.js
This change means that a player selecting meditate, but then not carrying out any meditation will recover their side action, which I've noticed is a common issue that players use Manual Mode to work around.
> Meditating 0 does not use side action

- data/cards/all-cards.json
- test/server/cards/ChainedCreations.spec.js
I added a test and removed the conjurations that Summon Salamander Monk and Summon Indiglow Creeper can't summon directly from all-cards.json. I confirmed that this doesn't stop decks from being considered invalid. **I am not sure if all-cards.json conjurations attribute is being used by any other functionality.**
Aside: Applying this change to the json config was annoying with Docker. I couldn't just do a normal rebuild (docker-compose build), I had to delete the container, then build from scratch.
> Bug fix #538 Chained Creations

- server/game/gamesteps/setup/FirstFivePrompt.js
Error in logic meant that selecting a greyed out card would remove the greyed out effect on remaining cards with the same name in the deck. Now only cleans up selection if the selected card was in hand.
> Fix bug for selecting greyed out cards during First Five selection

- server/game/gamesteps/MeditatePrompt.js
Fix issue #690 by initialising selected cards in the constructor. This appeared to fix the issue with Particle Shield, though perhaps there is a lingering issue that is causing the selected cards to remain from a reaction on the previous turn.
> Initialise selected cards when setting up meditate prompt

- server/game/gamesteps/ChooseDefendersPrompt.js
- test/server/attack-unseen.spec.js
The additional checks for validity will cause some issues when multiple unseen units are being blocked if the blocking player wants to reassign them. They will need to clear selections and start again. This is due to the code now checking only that we aren't reassigning a blocker to work around the CheckUnseen deficiency. Ideally, the check would confirm that the blocking reassignment would not lead to checkUnseen becoming false but I can't work out a simple way of doing this.
> Bug fix for unseen and terrifying

- server/game/cards/Ashes-Core/Hypnotize.js
- server/game/cards/Ashes-Core/NoahRedmoon.js
- server/game/cards/Ashes-Core/OutOfTheMist.js
- server/game/cards/Mixed-Expansions/LickWounds.js
- server/game/cards/Mono-Expansions/SecretDoor.js
- server/game/cards/Mono-Expansions/ToShadows.js
- server/game/cards/Time/HuntingWeapons.js
- test/server/cards/SecretDoor.spec.js
Secret Door - now restricted to units with a printed life of 1
Hypnotize - restricted to own units
Noah - fixed comment
Out of the Mist - can target any units
Lick Wounds - can target any PB or units
To Shadows - removed designation of any player as this doesn't appear to do anything.
Hunting Weapons - ping restricted to opposing units
> Fixed Secret Door check and other target restrictions

- server/game/cards/Mono-Expansions/RinsFury.js
- test/server/cards/RinsFury.spec.js
Forcing the target to be controlled by the opponent meant that autotarget would fail rather than accidentally target the defending unit
> Bug fix #766 Rins Fury destroys defending unit

- server/game/cards/Mono-Expansions/Copycat.js
- server/game/game.js
- server/game/gamesteps/triggeredabilitywindowtitles.js
- test/server/cards/Copycat.spec.js
- test/server/cards/Vanish.spec.js
As described in the targetting, I'm not sure what the intended functionality of GetTargettingTitlePhrase's first if statement was. It appears to assume if there is a good preThen event, that title should be presented to the player instead. The only test where this was relevant was Enchanted Violinist's Shared Sorrow, where it made Vanish appear as if it could react to the 1 damage being dealt, which is not really correct; Vanish is responding to the effect targetting the player in order to discard a card from their deck. So I think just commenting that out is fine, but please confirm if there is something I'm missing.
> Bug fix #777 Phoenix Barrage and Vanish reaction message isn't correct

- server/game/game.js
- server/game/player.js
- test/server/cards/GorrenrockBrawler.spec.js
I can fix the specific bug by reseting wasAttacker and wasDefender when the player ends their turn, but I'm not sure if this may have other consequences. For example, I'm not sure whether a unit that has had Strange Copy applied and will be destroyed at the end of turn should result in the Brawler gaining a status token. I'll ask Discord > Rules to confirm
> Bug fix #803 Gorrenrock Brawler and unit death on the subsequent turn

- server/game/GameActions/DiscardTopOfDeckAction.js
- server/game/cards/Ashes-Core/MistTyphoon.js
- server/game/cards/Mono-Expansions/ParticleShield.js
- server/game/cards/Time/Concentration.js
- server/game/cards/Time/FlockShepherd.js
- server/game/cards/Time/RubyCobra.js
Message fix for Ruby Cobra (now discard card is not automatically listed in the effect), also Flock Shepherd effect wording fix, and draw message when it is the second part of an effect.
> Improve discard and draw messages

- server/game/AbilityTargets/AbilityTargetCard.js
- test/server/cards/RinsFury.spec.js
Added tests to Rin's Fury that confirm that a random opponent's unit is being destroyed when the damage source is not a valid target. Also changed where the autotarget return is so that the user can see when the autotarget has failed and is prompted to select the unit for destruction.
The missing piece is: How can we cancel the destruction action only if the damage source is not a valid target?
> Rin's Fury and autotarget bug fix

- server/game/Card.js
- server/game/cards/Mixed-Expansions/MirrorSpirit.js
- test/server/cards/MirrorSpirit.spec.js
Fixed 2 bugs:
card.js method exhaustionGravityFlux wasn't searching for the right type of tokens and
Mirror Spirit wasn't counting gravityFlux tokens
> Bug fix #818 Mirror Spirit now counts gravity flux tokens

- server/game/cards/Time/Concentration.js
Minor fix. Probably no-one has noticed that they can unexhaust their opponent's die, because why would they do that?
> Concentration should only fix owner's die

- server/game/gamesteps/MeditatePrompt.js
Partial fix for FR #824. Meditate now says in words whether the die was previously on a basic or class side. I'd prefer to show the symbol of what it was, however I think I'd need to be able to use the levelState in some way or clone the die to achieve this.
> Meditate from message

- server/game/cards/Time/AdeptDuelist.js
- test/server/cards/AdeptDuelist.spec.js
Disarm should only affect alterations on opposing units. Added restriction and confirmed via enhanced tests
> Restrict Adept Duelist Disarm and enhance tests

- server/game/Die.js
- server/game/cards/Ashes-Core/BloodShaman.js
- server/game/cards/Ashes-Core/CallUponTheRealms.js
- server/game/cards/Ashes-Core/HiddenPower.js
- server/game/cards/Ashes-Core/ShiftingMist.js
- server/game/cards/Deluxe/Accelerate.js
- server/game/cards/Deluxe/MagicSyphon.js
- server/game/cards/Deluxe/ShatterPulse.js
- server/game/cards/Mixed-Expansions/ChangingWinds.js
- server/game/cards/Mixed-Expansions/DarkReaping.js
- server/game/cards/Mixed-Expansions/Hollow.js
- server/game/cards/Mixed-Expansions/NightsongCricket.js
- server/game/cards/Mixed-Expansions/TransmuteMagic.js
- server/game/cards/Mono-Expansions/ShadowSpirit.js
- server/game/cards/Mono-Expansions/Vanish.js
- server/game/cards/Mono-Expansions/VictoriaGlassfire.js
- server/game/cards/Time/DreamFracture.js
- server/game/cards/Time/DreamlockMage.js
- server/game/cards/Time/FoxSpirit.js
- server/game/cards/Time/VoidPulse.js
- test/server/attack-phoenixborn-removal.spec.js
- test/server/cards/BloodShaman.spec.js
- test/server/cards/Keepsake.spec.js
- test/server/cards/LawOfAssurance.spec.js
- test/server/cards/MagicSyphon.spec.js
- test/server/cards/Vanish.spec.js
- test/server/cards/VoidPulse.spec.js
- test/server/dice-cycle.spec.js
Significant level of changes. In summary:
- ChangeDice actions now trigger Vanish by checking the owner
- LowerDie actions now trigger Vanish by setting the targetsPlayer flag
- ChangeDice, LowerDie, RaiseDie & RerollDie consistently don't allow the die selected to be exhausted
I think that these changes together should resolve Issue #915
> Feature dice change targets

- server/game/cards/Mixed-Expansions/SummonFallen.js
Fixes bug that allowed selection of opponent's Summon Fallen books when both players had Status tokens on Summon Fallen
> Restrict summon fallen to self

- server/game/game.js
- server/game/player.js
- test/server/cards/SummonSleepingWidows.spec.js
I moved the limitedPlayed reset to the game.js endturn step, rather than having it inside player.js
I'm not sure if this is the best way of doing it, but it worked for the test that was originally failing as it ensured that the reaction counter was reset after the player endturn step.
> Reset reaction counter consistently

- client/Components/GameBoard/Card.jsx
Prevented card selection from being highlighted when it is in the deck
> Bug fix #935: Prevented highlighting the card that is on top of the deck

- Dockerfile
Fixes the Dockerfile for running the "lobby" and "node" services in docker-compose.
The node:16 base image does not have pangocairo available.  This results in "RUN npm install" failing if the library is not installed beforehand.
> Fix Dockerfile for Lobby/Node Services
